### ISSUE TITLE
Mounting of LUN with Azure Li config file

### ISSUE THREAD

**Issue by schaefi** [SUSE/azure-li-services#1]
Would it be possible that the filesystem which contains  the config file can be created with a persistent label name we can rely on ? That would allow us to do a simple  label based mount and we don't have to search the device. For example

``` bash
mount --label azconfig /mount_point
```

Depending on which filesystem you choose the volume label has a size limitation, usually 16bytes
I'm open for any name which works for you.

Thanks for your feedback

**Comment by jeffaco** [comment]
I'm okay with a label of `azconfig`. However, there's a lot of other aspects to a F/S (type, etc).

Please give me some basic commands of how you want the F/S to be formatted before we drop the configuration file onto it, thanks.

**Comment by schaefi** [comment]
If you choose a known non proprietary Linux filesystem all we need to know is the label because the mount call will be able to detect all aspects of the filesystem automatically given the driver exists in the kernel. So you are free to choose any of ext4, xfs, fat ... personally I would use ext4 which is then

```
mkfs.ext4 -L azconfig /dev/device
```
