### ISSUE TITLE
Clean-up of system after System Configuration

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#12]
There is currently an E-Mail discussion on handling of the YAML file upon completion of system configuration. I thought it would be best to continue that here.

In addition, after configuration, some run-once services are left around for azure-li-services as well. While it did offer some debugging capabilities, I think such debugging could be offered by log files as well. At first glance, I don't like the idea of run-once services left around. What if an administrator inadvertently runs one? Would any of them do damage to an already configured system?

Things to consider cleanup of include:

* YAML file, currently copied to /etc after it's found, is left around. Should it be deleted instead (I think yes, but it's a discussion issue),

* Service scripts (`azure-li-services`, `azure-li-services-network`, and more to follow) are left around. Should they be removed as part of configuration cleanup?

* Other artifacts of system configuration (other than log files) that may be in place.

I think any artifacts of the system configuration should be carefully considered. I like log files left around for diagnosis of problems, but I propose that all other configuration artifacts be removed during configuration cleanup.

**Comment by schaefi** [comment]
> YAML file, currently copied to /etc after it's found, is left around. Should it be deleted
> instead (I think yes, but it's a discussion issue),

Depends on our (suse) role of support in terms of problems. I would keep it, if non Microsoft engineers need to look at it

> Service scripts (azure-li-services, azure-li-services-network, and more to follow) are left around. 
> Should they be removed as part of configuration cleanup?

I agree with Robert here. To avoid accidental recall of the services we can just delete it. Which would mean a single uninstall of the azure-li-services package

**Comment by schaefi** [comment]
I'll continue with this service next.

@jeffaco I need to get your feedback whether the config file should stay on the system or not

Thanks

**Comment by schaefi** [comment]
ok that makes sense to me too
