### ISSUE TITLE
Take YAML file from DVD as fallback source

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#13]
We're still having problems mounting LUNs reliably from our Linux blade (will follow up with that offline after additional testing).

However, I've since learned that Azure data centers get these often use DVD drives to get data. As we're moving more towards automation of infrastructure, it's becoming easier for us to make a DVD visible to a blade upon boot.

Would it be possible to look for a LUN (as existing code does) for the YAML and, if the LUN doesn't exist, then look at the local DVD drive on the system? That gives us an option and might be easier for us in the future.

Please let me know, thanks.

**Comment by schaefi** [comment]
Sure if there is a /dev/dvd device on your system (which is normally the case as soon as one exists) I can run a mount on that device as fallback
