### ISSUE TITLE
Location and name of config file on LUN

### ISSUE THREAD

**Issue by schaefi** [SUSE/azure-li-services#2]
Would it be possible that the config file name and location on the filesystem is at a fixed position and name. This would avoid a filesystem search and leads to faster code

One suggestion from Jeff was

```
<lun_mount_point>/suse_firstboot_config.yaml
```

That would work for me but I'm also open for any name which works best for you

**Comment by schaefi** [comment]
The lun_mount_point is mentioned here to make clear we are looking up a file from another lun which needs to be mounted first. I agree it's immaterial for the decision about the name of the config file. 

However if for some reason the file is provided as part of a directory structure on the lun it's important for us to know that too and that's the reason why I explicitly tried to show a path and not only the base file name.

That we need to know the name and can't put it into the config file is probably clear to everybody :smile: 

However there would still be the opportunity to pass along a file name on the kernel command line
when the instance boots. I opened this issue because I don't know the direction the team at
Microsoft plans to go and would like to get them on board such that we can work together.

Things which seems completely clear to us might not be clear to others and vice versa. If my plan
works we will have the  microsoft/azure-li-services github team Jeff created added to this project and that brings the right people together.

**Comment by schaefi** [comment]
@jeffaco unless declined I'll take the suggestion of *suse_firstboot_config.yaml* as the name for the config file to be our decision. Let me know if there are objections from your team. Thanks

**Comment by jeffaco** [comment]
I'm fine with suse_firstboot_config.yaml. Closing issue.

**Comment by schaefi** [comment]
Thanks, but let's close when the issue gets merged. The close then happens automatically
