### ISSUE TITLE
Constraint checker service

### ISSUE THREAD

**Issue by schaefi** [SUSE/azure-li-services#30]
Add support for handling the machine_constraints section

```yaml
machine_constraints:
  min_cores: 32
  min_memory: "20tb"
```

**Comment by jeffaco** [comment]
Please be certain to take non-integer values, if possible. For example:

```
machine_constraints:
  min_cores: 32
  min_memory: "1.5tb"
```

Thanks.

**Comment by schaefi** [comment]
sure, there is a nice python module covering human input for int, float with several unit options which I regularly use for these type of input. You'll see it in the pull request coming soon
