### ISSUE TITLE
Need to disable EDAC (error detection/correction) on both LI and VLI systems

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#41]
This had come up with in a lunch conversation with our HPE vendor, and I had this on my list to look into. Then, it turns out, it came up during meetings with Operations on compute setup:

We need to disable EDAC in the O/S for both LI and VLI as the underlying hardware handles this. This is done by:

```
modprobe -r sb_edac edac_core
vim /etc/modprobe.d/blacklist.conf and add below lines:
  blacklist sb_edac
  blacklist edac_core
```

Can this capability be added? Would this need YAML extension, or could you just handle it automatically since it's done for both LI and VLI?

**Comment by rjschwei** [comment]
This happens during image build, not at runtime.

I modified the image build setup and bumped the image version to 1.0.31
