### ISSUE TITLE
SSH configuration for access to storage

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#42]
Final issue that came up in meetings with Operations:

We need to configure SSH for access to storage. This is done by SSH public/private key configuration:

* SSH key is generated from O/S
  * Private key stored in `/root/.ssh/id_dsa`
  * Public key is added to storage

This is currently done with a command like `ssh-kengen -t dsa -b xxx`.

It would be a pain to get the public key off of the system (after generating the password hashes, we don't save the source password(s), if any). So I propose we generate the key elsewhere and then add the private key to the YAML file to be stored in `/root/.ssh/id_dsa`. Perhaps, in the credentials section, add:

```
username: root
...
private_key:
  name: /root/.ssh/id_dsa
  ssh-key: "XXXXX"
```

Thoughts?

**Comment by schaefi** [comment]
Hmm, not sure if we want to transport a secret private key in the config file.

> This is currently done with a command like ssh-kengen -t dsa 

I guess you meant ssh-keygen command. I also think dsa keys are not secure enough and suggest
to put on rsa algoritm

Usually the public id is copied from the machine asking for access to the machine which grants access

```
# on machine asking for access
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa_storage
ssh-copy-id -i ~/.ssh/id_rsa_storage user@storage
```

the copy-id will ask for a password, so this is probably the reason why we can't got that route, correct ?
Just to mention it's possible to pass in the password but it will violate security in the same way as providing the private key in the config file.

> So I propose we generate the key elsewhere

and how should that work ? Meaning who or what creates the key-pair ? and who or what makes
sure that the public key lands in the authorized_keys file of the storage machine ? Imho there must be a way to access storage and put that information in. If we could make use of that access strategy it would also be possible to create the key-pair on the instance and "somehow" copy the public key to the storage machine

Technically it's no problem for us to copy a given private key to some place on the system. So far we tried hard to keep the config file free from any security issues but that suggestion will open one to my understanding.

**Comment by jeffaco** [comment]
I was thinking that automation would generate the key pair during setup of storage. That is, during automation, we generate the key pair, and then when automation was setting up storage, the public key would be stored on storage and the private key would be put in the image so we can get to storage.

I'm sensitive to the security aspect of items in the YAML. But that said, we're careful about YAML permissions. But, on the other hand, that caused all the other design discussion where we don't put raw passwords in the YAML either, but put in the shadow hash entry.

I'm uncertain why Operations is using dsa vs. rsa. These are all restricted VLANs, which helps, but still, it seems like rsa is a better choice. I'll ask the operations folks.

The reason I'd like this in the YAML: I don't necessarily know the password (after creating the shadow password, I don't store it anywhere). And there may not even be a password configured. To be secure, the customer would choose no password and a public key based on a private key with a passphrase. In that case, I couldn't log into the system to set up the key myself during automation. Thus, that's not really an option.

One choice is that the private key be elsewhere (beside the YAML), with a pointer to the file within the YAML. But as discussed when setting up passwords, that's just a redirection to help avoid a mistake.

On the bright side, we control this key. So if there's a problem, we could trivially regenerate it.

Given the constraints of (lack of) access to the system after deployment, what do you suggest?

**Comment by rjschwei** [comment]
Yes, we have no way to communicate back thus the secure way to do this, i.e. generate the key on the user system is blocked.

Lets look at the effect of this:

With possession of the private key a person has full access to the customer data store, and that's pretty bad, IMHO.

Now lets look at how an adverse actor would get this private key:

- The key is copied right after generation by the adverse actor:
  + This implies that the actor has access to the automation code and either modifies the source code in some repository or modifies the automation code on the system that holds the generator.
     ~ The mitigation is strict but enforceable. People that have access to the YAML generator source, either in the repo or on the system where the generator runs should not have access permissions to the storage backend.
- The YAML is copied for debuging purposes:
  + At this point all bets are off as the YAML file is easily stuck into an e-mail and then the private key is out in the world and the mitigation for the first issue makes no difference anymore.

So how do we fix this? I know the million dollar question ;)

Once the connection is made between the systems we can replace the key, meaning we can generate a new ssh key on the users system. Then add that to the storage host. We can then remove the previous private key on the compute host and remove the original public key from the storage host. While that's a bunch of copying of stuff it exposes the customer system for only a short period of time and an adverse actor would have to do a lot more than to get a hold of the key generate during YAML generation.

Also the key replacement ensures that the key in the YAML file becomes useless.

IMHO it is well worth the effort to implement a key-replacement procedure in the setup code.

**Comment by jeffaco** [comment]
Some of security concerns are eased because of VLAN arrangements (a key is only valid on a particular VLAN that the customer doesn't have access to). But obviously, any sort of error in setup means that all bets are off.

I thought about this. Another approach is that the setup code generate the private key file itself. But then how would the system get us the public file to put on the NetApp? If we could work that out, then the private key stays on the system, secured. Any ideas?

I proposed what I proposed because of this question. Without being able to get public key (no access to the system, remember), I didn't think the target O/S could generate it.

**Comment by schaefi** [comment]
>Once the connection is made between the systems we can replace the key, meaning we can >generate a new ssh key on the users system. Then add that to the storage host. We can then >remove the previous private key on the compute host and remove the original public key from the >storage host. While that's a bunch of copying of stuff it exposes the customer system for only a short >period of time and an adverse actor would have to do a lot more than to get a hold of the key >generate during YAML generation.

I like this idea. We can see the private key as a temporary door opener to access storage.

So on the instance we can create a new key-pair (ssh-keygen) and copy the identity via (ssh-copy-id) using the existing private key which ensures that this can be done without further credentials. After that the door opener private key pair should be deleted

We could even think of deleting the pub key from the authorized_keys file on the storage machine. Not sure if this is wanted ?

**Comment by schaefi** [comment]
>it would take customer/Operations interaction to make a key swap happen, along with access rights >and/or E-Mail (or whatever) to gain access to the the public key. And further coordination when
>the key >was actually replaced on the NetApp. In short, yuck.

ok I thought the ssh key pair is only distributed between machines. But it seems the customer uses it and that makes it a complex task when the key changed. In this case let's go with the current implementation and hope you are right that only trusted parties have access to the yaml config

>Is there some way we can encrypt this and securely share the secret with the destination system?

We could use a symetric key for encryption/decryption and put the key into the image. After decrypt that key would be deleted from the system. A potential attacker would then need both: access to the yaml config and access to the machine or the image file. If there is access to the machine all bets are off anyway.

If the key changes a rebuild of the image on the suse side would be required. That's the downside of this approach.

In any case we could add that encryption method as a separate pull request and if we go that way I suggest to open a new issue for it

**Comment by rjschwei** [comment]
This is not really closed yet, I think. We have an initial implementation but want to improve.

OK bummer that we cannot change the key. I guess the ssh public-key is stored in the NetApp control plane somewhere :(

I agree with Marcus that the path of encrypting the key in the YAML creates a lot of overhead. Not only from a change perspective but we also have to safe-keep the key withing SUSE somehow, which means we couldn't really build the image as the encryption key could certainly not be checked into the Build Service where the image is being built.

That really leaves us with the current implementation. The only thing I would add is that we modify the YAML when we are done and remove the ssh key. This prevents the issue of having the sensitive key e-mailed around by accident.

Customer: Hi, my system is not provisioned
Msft support: Please e-mail me your YAML file

and now it's too late and the key is in the wild. So if we stick the key in the YAML file the YAML file should be re-written without the key when the setup is done. The other option is to use indirection, i.e. the attached lun (or virtual DVD for Gen 3) also contains a private_ssh_storage.key file which is referred to in the YAML. That way the key doesn't get e-mailed around the world by accident.
