### ISSUE TITLE
Service azure-li-storage signals error when none exists

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#43]
Due to problems with `azure-li-machine-constraints`, my `/etc/issue` file has:

```
linux:~ # cat /etc/issue

!!! DEPLOYMENT ERROR !!!
For details see: "systemctl status azure-li-machine-constraints azure-li-storage"

linux:~ #
```

Looking at `azure-li-storage`, I see no problems (indeed, my YAML doesn't configure that yet - I'm testing that next):

```
linux:~ # systemctl status azure-li-storage
* azure-li-storage.service - Setup of Azure Li/VLi Storage Mountpoints
   Loaded: loaded (/usr/lib/systemd/system/azure-li-storage.service; bad; vendor preset: disabled)
   Active: inactive (dead) since Tue 2018-06-19 15:27:25 UTC; 29min ago
 Main PID: 26652 (code=exited, status=0/SUCCESS)

Jun 19 15:27:25 linux systemd[1]: Starting Setup of Azure Li/VLi Storage Mountpoints...
Jun 19 15:27:25 linux systemd[1]: Started Setup of Azure Li/VLi Storage Mountpoints.
Warning: azure-li-storage.service changed on disk. Run 'systemctl daemon-reload' to reload units.
linux:~ #
```

Why is this mentioned in `/etc/issue` when it's not actually a problem?

**Comment by schaefi** [comment]
The overall success flag for storage is set if at least one entry to fstab was added. If you have an empty storage section in your config file it is considered an error. How does your storage section look like ?

* I agree we are missing a good error message that nothing was added to fstab
* or we consider an empty storage section to be ok

**Comment by jeffaco** [comment]
Ah, I don't have a storage section today. Storage is currently not mandatory in the YAML. If a section isn't mandatory in the YAML, then lack of that section shouldn't trigger an error, in my opinion.

I'll be testing storage shortly. But going forward, if we don't want storage (for whatever reason), we won't have the section.

**Comment by schaefi** [comment]
agreed, this needs a fix. I'll look at it

**Comment by schaefi** [comment]
same applies to packages, call and machine_constraints sections which are also not mandatory
