### ISSUE TITLE
VLI: Systems may not reboot without operator intervention

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#46]
In certain cases, our VLI systems may not reboot automatically without operator intervention. This is a problem if a customer tries to reboot a system and would then need to contact operations to get the system back up.

In chatting with HPE about this, one of their engineers said:

>> Autorebooting - startup.nsh is just one option. HPE has no opinion on a preferred method of autobooting. So your choice
>
>startup.nsh has a decided advantage of surviving both bios updates and ‘power -c reset’. The latter being a useful tool for clearing up some ‘logical’ problems and *slso* required after a BIOS update. So, in my opinion, startup.nsh is preferred over setting a BIOS boot option through the Bios menu.

So while HPE themselves has no opinion on setting up autoboot, their engineers like it, and so do I. We do this as follows:

```
echo "fs0:\efi\sles_sap\grubx64.efi" > /boot/efi/startup.nsh
```

Weird that the file as `\` characters in it, but I imagine you folks understand this better than I do. We'd like this to be set up automatically for VLI platforms.

**NOTE: This is specific to VLI - Very Large Instance - platforms!**

**Comment by rjschwei** [comment]
Generally this would go into the image build and at present doesn't really fit with any of the services. So lets hold off on this until we come to a conclusion on the Gen3/Gen4 e-mail discussion.

**Comment by schaefi** [comment]
efi startup scripts in /boot can't be configured through the image description with the legacy kiwi builder.

It would be easier to create an e.g azure-li-system-setup.service and handle setup tasks like this in clean code. That way we could also distinguish between tasks for LargeInstance and VeryLargeInstance.

I think we should aim for an image which is generic in both environments LI and VLI and everything which needs to be handled instance specific should be done in this project. As long as one image can boot in both environments this will work

**Comment by jeffaco** [comment]
I'm leaning that way too. It also helps avoid "image explosion" (a very large number of different images that must be generated).

We'll learn, early in the VLI development stage, just how possible this is. But if we can keep a single image for both LI and VLI, that's easier for both of us.

I entered this as a placeholder so it won't get lost. I'll prefix all VLI specific issues with `VLI:` so we can start looking at them together, likely mid July, when I return from my vacation. Hopefully that works for you guys.
