### ISSUE TITLE
delete ssh-private-key from yaml after processing

### ISSUE THREAD

**Issue by schaefi** [SUSE/azure-li-services#58]
Once processed the ssh-private-key should be deleted from the yaml file. This imho can be done as part of the cleanup service

**Comment by schaefi** [comment]
alternative the key reading can be changed such that the key is not stored in the yaml file but as a file on the external location the yaml file is beeing stored on too

**Comment by schaefi** [comment]
So this is basically a question for @jeffaco 

1. do we want to handle the key as extra file on lun (or iso)
2. do we want to handle the key as element in the config file

I would prefer 1.

**Comment by jeffaco** [comment]
If I'm already creating a LUN with the YAML (or a DVD with the YAML), then it seems easy enough do provide the key as an extra file.

It shouldn't be any harder for me, and it eliminates the cleanup issue for you (copy the YAML, don't otherwise worry about it).

So my vote would be for 1 as well.

**Comment by schaefi** [comment]
:+1: great I'll change the code to reflect this. Thanks
