### ISSUE TITLE
Design of the package installer service

### ISSUE THREAD

**Issue by schaefi** [SUSE/azure-li-services#7]
There is the packages section in the yaml config as follows:

```yaml
packages:
  directory: "/mnt/directory-with-rpm-files"
  directory: "/mnt/another-directory-with-rpm-files"
```

I'd like to start a discussion on how those packages should become installed

Basically there are two options:

1. Take all packages from the listed directories and install them the brute force way by calling ```rpm```

2. Create a clean repository from the packages using the ```createrepo``` tool, register that repo to the zypper packagemanager and install all packages in a transaction with the ```zypper``` tool

I vote to do it "right" with option 2. That's because of the following reasons:

* A package install transaction through zypper checks for consistency and dependencies and allows to resolve all package dependencies in a clean way. Of course there is also potential that this fails resulting in the package to be not installable

* A package installation via zypper takes all other configured repositories into account and helps to keep the system integrity intact

* A package installation via zypper provides good error messages in terms of problems with dependencies, conflicts and others

The brute force way ignores all that and brain dead installs data on the machine which I personally would not do. If there are no objections I'll implement option 2.

Thoughts ?

**Comment by rjschwei** [comment]
I also favor using zypper. That said the things we have to consider are:

1.) The customer is not in a position to help themselves if there is an issue with package installation
   - For example, if network drivers do not install then there is no network. In the brute force approch packages would install but there is still no certain way to know that the drivers will actually work, thus there i sno advantage for the brute force approach.
2.) The packages would need to be provided on external lun, possibly the temporary lun that also holds the YAML file
    - Meaning after use the added repositories have to be removed or the next time the customer wants to use zypper they will get an error
3.) We have to figure out how to handle signatures and vendors
    - For vendors we can use an equivalence file if needed
    - For signatures we can decide to simply accept the packages even if GPG check fails, but that needs to be an explicit agreement, which is why we are having this discussion ;)

**Comment by jeffaco** [comment]
I'm okay with this. But in the end, what would we do here? Do we put the package repo on the YAML LUN along with the YAML file?

Would zypper work without network connectivity?

If we added the repo to the zypper packagemanager, then would you remove the repo when done? If so, then what happens later when packages need to be updated?

We won't have any sort of a "stable repository" for drivers here in our infrastructure. So given that, I'm not 100% sure that zypper is all that useful (although brute force `rpm --install` isn't beautiful either).

Questions on how to handle signatures and stuff open, as pointed out by Robert. Those go away too with "raw" RPMs, but raw RPMs are not pretty.

**Comment by schaefi** [comment]
> The packages would need to be provided on external lun, possibly the temporary lun that also holds
>  the YAML file

yes I suggest to put the .rpm package files on the lun which also has the yaml file. In the yaml we have this:

```
packages:
  directory: "directory/with/rpm-files"
```

I would expect that directory to exist on the lun.

> Meaning after use the added repositories have to be removed or the next time the customer
> wants to use zypper they will get an error

My plan was to copy all packages from all specified directories off the lun and into the system to
e.g ```/etc/localrepos/NAME``` The name (NAME) of the directory could be specified in yaml packages
section, or we just pick a generic name

I would now create a real repo with metadata from ```/etc/localrepos/NAME``` and register that as a repo in zypper. Next the installation of those packages with zypper will follow. That way the repo can stay on the system as local repo which is imho important because this will keep any further transaction
consistent.

If we just register a temporary repo, install and forget it again we leave a system with packages(s) installed from a ghost location which I would like to avoid.

> Would zypper work without network connectivity?

yes, using the local cache

> For signatures we can decide to simply accept the packages even if GPG check fails, but that needs > to be an explicit agreement, which is why we are having this discussion ;)

In the service code I would call zypper with an option to accept the gpg key. The source for the packages are the lun which I consider a trusted source. If we need gpg verification the packages must be signed with a key we know. If that key is unknown to us it must be imported first. Which means the key needs to be put on the lun too, or if it is always the same key we can embed it into the image at build time

**Comment by rjschwei** [comment]
It is mostly going to be about 3rd party packages. For example on the VLI implementation we need packages from HP. Those packages are not accessible in the Solid Driver Build Service and cannot be downloaded on the fly. I expect that HP signs their packages. Never the less we can treat those packages as trusted as it will be up to the Microsoft Ops team to download the packages, verify origin and signature and then make them available on the lun for installation.

**Comment by schaefi** [comment]
yes which is why I thought everything read from the lun can be considered a trusted source

**Comment by jeffaco** [comment]
I concur. Given that the packages are in the same location as the YAML, I don't see a value to the `gpg_key:` field. Let's not move forward with that.
