### ISSUE TITLE
Need capability to select, via YAML, if crash dump should be enabled

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#78]
On VLI systems with 12+TB of RAM, crash dumps can take quite a while.

Is it possible, within the YAML file, to select if crash dumps are enabled or disabled? Perhaps something like:

```
crash-dump: enabled | disabled
```

If not specified in YAML, then crash dump should be as is (enabled).

**Comment by schaefi** [comment]
I'll add

```yaml
crash_dump: true|false
```
