### ISSUE TITLE
LI Testing: Missing Packages

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#80]
In the [SUSE Linux Enterprise Serv er 12.x for SAP Applications Configuration Guide for SAP HANA](https://1drv.ms/b/s!AtCDpQuLZQRZr2WzXQx_fwHsGLkX), in Section 8.1, there is a package list of packages that should be installed. We are missing some of these.

While this list is not exhaustive, we are missing at least:

* iptraf
* findutils-locate
* audit-libs
* keyutils-libs
* perl-Time-Piece (needed for backup scripts)
* syslog-ng

I can go through for a more exhaustive list, if needed. But based on our docs, we need those packages for support or proper operations.

Can you please review section 8.1 and let me know your thoughts, thanks.

**Comment by schaefi** [comment]
ok I'll take a look and add them to the image build

**Comment by schaefi** [comment]
yes it's there, simple test:

```perl
use Time::Piece
```

just works, no extra module package needed

**Comment by schaefi** [comment]
I've added all the rest of the package to our image:

```xml
<!-- requested by SAP Applications Configuration Guide for SAP HANA -->
        <package name="iptraf"/>
        <package name="findutils-locate"/>
        <package name="audit-libs"/>
        <package name="keyutils-libs"/>
        <package name="syslog-ng"/>
```

Please note syslog-ng conflicts with rsyslog which was added before. I deleted rsyslog as it seems you guys prefer syslog-ng

**Comment by schaefi** [comment]
Fixed in image build
