### ISSUE TITLE
LI Testing: kmod-usnmic_verbs is missing from pacakges installed

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#85]
Note the following output:

```
soltyo32:~†# rpm -qa | grep -i kmod
kmod-compat-17-9.6.1.x86_64
libkmod2-17-9.6.1.x86_64
* kmod-usnic_verbs-1.1.545.8.sles12sp3-1.x86_64
kmod-17-9.6.1.x86_64
```

The line marked with "*" is missing on the test image, and we normally have this (and check for it). What is this, and should we have it?

**Comment by schaefi** [comment]
This provides the driver for the usNIC feature of the Cisco VIC SR-IOV Ethernet NIC. 

The driver is provided by us in the enterprise buildservice as follows:

```
<package name="cisco-enic-usnic-kmp-default"/>
```

So your check needs to be adapted to look for that name.

In general at suse kernel module packages are not named kmod they are named kmp-<kernel-name>
